2'nd variant of last version of the 'shield' function. Exec string in it's 'single quotas' - expantion only eval command.

diff --git a/folding b/folding
--- a/folding
+++ b/folding
@@ -405,18 +405,6 @@ echo "options 2 is: $@" >&2
 while true ; do
 #    echo "current option is: $1"
     case "$1" in
-#     -a|--a-long) echo "Option a" ; shift ;;
-#     -b|--b-long) echo "Option b, argument \`$2'" ; shift 2 ;;
-#     -c|--c-long)
-# 	# c has an optional argument. As we are in quoted mode,
-# 	# an empty parameter will be generated if its optional
-# 	# argument is not found.
-# 	case "$2" in
-# 	"") echo "Option c, no argument"; shift 2 ;;
-# 	*)  echo "Option c, argument \`$2'" ; shift 2 ;;
-# 	esac ;;
-#     --) shift ; break ;;
-#     *) echo "Internal error!" ; exit 1 ;;
 
     -h|--help)
 	usage
@@ -435,6 +423,10 @@ while true ; do
     -*)
 	allopts="$allopts ${1}" ;;
     # Explicitly ignore non-option arguments, for compatibility.
+    *)
+	echo "Internal error!"
+	exit 1 ;;
+
     esac
     shift
 done
